froide_govplan/urls.py
from django.urls import path
from django.utils.translation import pgettext_lazy

from .views import (
    GovPlanDetailView,
    GovPlanProposeUpdateView,
    GovPlanSectionDetailView,
    search,
)

app_name = "govplan"

urlpatterns = [
    path("search/", search, name="search"),
    path(
        pgettext_lazy("url part", "<slug:gov>/plan/<slug:plan>/"),
        GovPlanDetailView.as_view(),
        name="plan",
    ),
    path(
        pgettext_lazy("url part", "<slug:gov>/plan/<slug:plan>/propose-update/"),
        GovPlanProposeUpdateView.as_view(),
        name="propose_planupdate",
    ),
    path(
        pgettext_lazy("url part", "<slug:gov>/<slug:section>/"),
        GovPlanSectionDetailView.as_view(),
        name="section",
    ),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(
        "follow/",
        include("froide.follow.urls", namespace="follow"),
    ),
    path("admin/", admin.site.urls),
    path("", include("cms.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

froide_govplan/models.py
import functools
import re
from datetime import timedelta
from urllib.parse import urlparse

from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from filer.fields.image import FilerImageField
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase

from froide.follow.models import Follower
from froide.georegion.models import GeoRegion
from froide.organization.models import Organization
from froide.publicbody.models import Category, Jurisdiction, PublicBody

from . import conf
from .utils import make_request_url

try:
    from cms.models.fields import PlaceholderField
    from cms.models.pluginmodel import CMSPlugin
except ImportError:
    CMSPlugin = None
    PlaceholderField = None


if conf.GOVPLAN_ENABLE_FOIREQUEST:
    from froide.foirequest.models import FoiRequest
else:
    FoiRequest = None


class PlanStatus(models.TextChoices):
    NOT_STARTED = ("not_started", _("nicht begonnen"))
    STARTED = ("started", _("begonnen"))
    PARTIALLY_IMPLEMENTED = ("partially_implemented", _("teilweise umgesetzt"))
    IMPLEMENTED = ("implemented", _("umgesetzt"))
    DEFERRED = ("deferred", _("verschoben"))


STATUS_CSS = {
    PlanStatus.NOT_STARTED: "light",
    PlanStatus.STARTED: "primary",
    PlanStatus.PARTIALLY_IMPLEMENTED: "warning",
    PlanStatus.IMPLEMENTED: "success",
    PlanStatus.DEFERRED: "danger",
}


class PlanRating(models.IntegerChoices):
    TERRIBLE = 1, _("terrible")
    BAD = 2, _("bad")
    OK = 3, _("OK")
    GOOD = 4, _("good")
    EXCELLENT = 5, _("excellent")


class Government(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("name"))
    slug = models.SlugField(max_length=255, unique=True, verbose_name=_("slug"))

    public = models.BooleanField(default=False, verbose_name=_("is public?"))
    jurisdiction = models.ForeignKey(
        Jurisdiction,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("jurisdiction"),
    )
    georegion = models.ForeignKey(
        GeoRegion,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("georegion"),
    )
    description = models.TextField(blank=True, verbose_name=_("description"))

    start_date = models.DateField(null=True, blank=True, verbose_name=_("start date"))
    end_date = models.DateField(null=True, blank=True, verbose_name=_("end date"))

    planning_document = models.URLField(blank=True, verbose_name=_("planning document"))

    class Meta:
        verbose_name = _("Government")
        verbose_name_plural = _("Governments")

    def __str__(self):
        return self.name

    @property
    def days_available(self):
        if self.start_date is None:
            return 0
        if self.end_date is None:
            return 0
        return (self.end_date - self.start_date).days

    @property
    def days_left(self):
        if not self.end_date:
            return 0
        now = timezone.now().date()
        if now > self.end_date:
            return 0
        return (self.end_date - now).days

    def days_used_percentage(self) -> int:
        total_days = self.days_available
        if not total_days:
            return 0
        now = timezone.now().date()
        days_used = (now - self.start_date).days
        return int(days_used / total_days * 100)


class CategorizedGovernmentPlan(TaggedItemBase):
    tag = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="categorized_governmentplan"
    )
    content_object = models.ForeignKey("GovernmentPlan", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Categorized Government Plan")
        verbose_name_plural = _("Categorized Government Plans")


WORD_RE = re.compile(r"^\w+$", re.IGNORECASE)


class GovernmentPlanManager(models.Manager):
    SEARCH_LANG = "german"

    def get_search_vector(self):
        fields = [
            ("title", "A"),
            ("description", "B"),
            ("quote", "B"),
        ]
        return functools.reduce(
            lambda a, b: a + b,
            [SearchVector(f, weight=w, config=self.SEARCH_LANG) for f, w in fields],
        )

    def search(self, query, qs=None):
        if not qs:
            qs = self.get_queryset()
        query = query.strip()
        if not query:
            return qs
        search_queries = []
        for q in query.split():
            q = q.strip()
            if not q:
                continue
            if WORD_RE.match(q):
                sq = SearchQuery(
                    "{}:*".format(q), search_type="raw", config=self.SEARCH_LANG
                )
            else:
                sq = SearchQuery(q, search_type="plain", config=self.SEARCH_LANG)
            search_queries.append(sq)

        if not search_queries:
            return qs
        search_query = functools.reduce(lambda a, b: a & b, search_queries)

        search_vector = self.get_search_vector()
        qs = (
            qs.annotate(rank=SearchRank(search_vector, search_query))
            .filter(rank__gte=0.1)
            .order_by("-rank")
        )
        return qs


class GovernmentPlan(models.Model):
    government = models.ForeignKey(
        Government, on_delete=models.CASCADE, verbose_name=_("government")
    )
    title = models.CharField(max_length=255, verbose_name=_("title"))
    slug = models.SlugField(max_length=255, unique=True, verbose_name=_("slug"))

    image = FilerImageField(
        null=True,
        blank=True,
        default=None,
        verbose_name=_("image"),
        on_delete=models.SET_NULL,
    )

    description = models.TextField(blank=True, verbose_name=_("description"))
    quote = models.TextField(blank=True, verbose_name=_("quote"))
    public = models.BooleanField(default=False, verbose_name=_("is public?"))
    due_date = models.DateField(null=True, blank=True, verbose_name=_("due date"))
    measure = models.CharField(max_length=255, blank=True, verbose_name=_("measure"))

    status = models.CharField(
        max_length=25,
        choices=PlanStatus.choices,
        default="not_started",
        verbose_name=_("status"),
    )
    rating = models.IntegerField(
        choices=PlanRating.choices, null=True, blank=True, verbose_name=_("rating")
    )

    reference = models.CharField(
        max_length=255, blank=True, verbose_name=_("reference")
    )

    categories = TaggableManager(
        through=CategorizedGovernmentPlan, verbose_name=_("categories"), blank=True
    )
    responsible_publicbody = models.ForeignKey(
        PublicBody,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("responsible public body"),
    )

    organization = models.ForeignKey(
        Organization,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("organization"),
    )

    group = models.ForeignKey(
        Group, null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_("group")
    )

    proposals = models.JSONField(blank=True, null=True)
    properties = models.JSONField(blank=True, default=dict)

    objects = GovernmentPlanManager()

    class Meta:
        ordering = ("reference", "title")
        verbose_name = _("Government plan")
        verbose_name_plural = _("Government plans")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "govplan:plan", kwargs={"gov": self.government.slug, "plan": self.slug}
        )

    def get_absolute_domain_url(self):
        return settings.SITE_URL + self.get_absolute_url()

    def get_absolute_short_url(self):  # Return long url as short url for update emails
        return self.get_absolute_url()

    def get_absolute_domain_short_url(self):
        return settings.SITE_URL + self.get_absolute_short_url()

    def get_reference_links(self):
        if self.reference.startswith("https://"):
            return [self.reference]
        refs = [x.strip() for x in self.reference.split(",")]
        return [
            "{}#p-{}".format(self.government.planning_document, ref) for ref in refs
        ]

    def get_section(self):
        return GovernmentPlanSection.objects.filter(
            categories__in=self.categories.all()
        ).first()

    def update_from_updates(self):
        last_status_update = (
            self.updates.all().filter(public=True).exclude(status="").first()
        )
        if last_status_update:
            self.status = last_status_update.status
        last_rating_update = (
            self.updates.all().filter(public=True).exclude(rating=None).first()
        )
        if last_rating_update:
            self.rating = last_rating_update.rating
        if last_status_update or last_rating_update:
            self.save()

    def get_status_css(self):
        return STATUS_CSS.get(self.status, "")

    def make_request_url(self):
        if not self.responsible_publicbody:
            return []
        return make_request_url(self, self.responsible_publicbody)

    def has_recent_foirequest(self):
        frs = self.get_related_foirequests()
        ago = timezone.now() - timedelta(days=90)
        return any(fr.created_at > ago for fr in frs)

    def get_recent_foirequest(self):
        return self.get_related_foirequests()[0]

    def get_foirequest_reference(self):
        return "govplan:plan@{}".format(self.pk)

    def get_related_foirequests(self):
        if FoiRequest is None:
            return []
        if not self.responsible_publicbody:
            return []
        if hasattr(self, "_related_foirequests"):
            return self._related_foirequests

        self._related_foirequests = (

froide_govplan/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, UpdateView

from .auth import get_visible_plans
from .forms import GovernmentPlanUpdateProposalForm
from .models import Government, GovernmentPlan, GovernmentPlanSection


class GovernmentMixin:
    def dispatch(self, *args, **kwargs):
        self.get_government()
        return super().dispatch(*args, **kwargs)

    def get_government(self):
        filter_kwarg = {}
        if not self.request.user.is_authenticated or not self.request.user.is_staff:
            filter_kwarg["public"] = True
        self.government = get_object_or_404(
            Government, slug=self.kwargs["gov"], **filter_kwarg
        )


class GovPlanSectionDetailView(GovernmentMixin, DetailView):
    slug_url_kwarg = "section"
    template_name = "froide_govplan/section.html"

    def get_queryset(self):
        return GovernmentPlanSection.objects.filter(
            government=self.government
        ).select_related("government")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = get_visible_plans(self.request)
        context["plans"] = context["object"].get_plans(queryset=queryset)
        return context


class GovPlanDetailView(GovernmentMixin, DetailView):
    slug_url_kwarg = "plan"
    template_name = "froide_govplan/detail.html"

    def get_queryset(self):
        qs = GovernmentPlan.objects.filter(government=self.government)
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return qs
        return qs.filter(public=True).select_related(
            "responsible_publicbody", "organization"
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["updates"] = self.object.updates.filter(public=True).order_by(
            "-timestamp"
        )
        context["section"] = self.object.get_section()
        if self.request.user.is_authenticated:
            context["update_proposal_form"] = GovernmentPlanUpdateProposalForm()
        # For CMS toolbar
        self.request.govplan = self.object
        return context


class GovPlanProposeUpdateView(GovernmentMixin, LoginRequiredMixin, UpdateView):
    slug_url_kwarg = "plan"
    form_class = GovernmentPlanUpdateProposalForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return redirect(self.object)

    def get_queryset(self):
        qs = GovernmentPlan.objects.filter(government=self.government)
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return qs
        return qs.filter(public=True)

    def get_success_url(self):
        return self.object.get_absolute_url()

    def form_valid(self, form):
        form.save(self.object, self.request.user)
        messages.add_message(
            self.request,
            messages.INFO,
            _(
                "Thank you for your proposal. We will send you an email when it has been approved."
            ),
        )
        return redirect(self.object)

    def form_invalid(self, form):
        messages.add_message(
            self.request,
            messages.ERROR,
            _("There's been an error with your form submission."),
        )
        return redirect(self.object)


def search(request):
    q = request.GET.get("q", "")
    plans = GovernmentPlan.objects.filter(public=True)
    if q:
        plans = GovernmentPlan.objects.search(q, qs=plans)

    if request.GET.get("government"):
        try:
            gov_id = int(request.GET["government"])
            plans = plans.filter(government_id=gov_id)
        except ValueError:
            pass
    if request.GET.get("status"):
        try:
            status = request.GET["status"]
            plans = plans.filter(status=status)
        except ValueError:
            pass

    if q:
        # limit when there's a search
        plans = plans[:20]
    return render(
        request, "froide_govplan/plugins/card_cols.html", {"object_list": plans}
    )

froide_govplan/templates/froide_govplan/plugins/card_cols.html
{% load thumbnail %}
{% load i18n %}
{% load govplan %}

{% if object_list|length == 0 %}
  <p>
    {% trans "Could not find any results. Try different keywords or browse the categories." %}
  </p>
{% else %}

<div class="row">
  {% for object in object_list %}
    <div class="col col-12 col-md-6 col-lg-4 d-flex mb-3">
      <a href="{{ object.get_absolute_url }}" class="d-flex w-100 text-body text-decoration-none">
        <div class="card-wrapper" style="border: 1px solid #000000;">
          <div class="box-card border-blue w-100 bg-body shadow-blue">
              <div class="box-card-header p-3 text-bg-callout" style="background-color: #502379; ">
                <h3 class="h6 m-0" style="color: #ccc;">
                  {{ object.title }}
                </h3>
              </div>
            <div class="p-3 tight-margin d-flex flex-column">
              {% if object.quote %}
              <blockquote>
                {{ object.quote|striptags|truncatewords:20|addquotes }}
              </blockquote>
              {% endif %}
              <div class="d-flex mt-auto">
                <span href="{{ object.get_absolute_url }}" class="action-link text-blue-600">
                  → mehr lesen
                </span>
                <div class="ms-auto">
                  <span class="badge text-bg-{{ object.get_status_css }}">
                    {{ object.get_status_display }}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>
  {% endfor %}
</div>
{% endif %}

froide_govplan/templates/froide_govplan/plugins/default.html
<ul>
  {% for object in object_list %}
    <li>
      <a href="{{ object.get_absolute_url }}">
        {{ object.title }}
      </a>
    </li>
  {% endfor %}
</ul>

froide_govplan/templates/froide_govplan/plugins/progress.html
{% load govplan %}

{% get_plan_progress object_list as progress %}

<div class="d-flex align-items-center">
  <span class="text-body-secondary{% if not instance.extra_classes or "progress-lg" not in instance.extra_classes %} small{% endif %}">{{ progress.count }} Vorhaben</span>
  <div class="flex-grow-1 ms-2">
    <div class="progress" {% if "progress-lg" in instance.extra_classes %}style="height: 1.5rem;"{% endif %}>
      {% for section in progress.sections %}
        <div class="progress-bar bg-{{ section.css_class }}" role="progressbar" style="width: {{ section.css_percentage }}%;" aria-valuenow="{{ section.css_percentage }}" aria-valuemin="0" aria-valuemax="100" aria-label="{{ section.percentage }}% {{ section.label }}" title="{{ section.percentage }}% {{ section.label }}" data-bs-toggle="tooltip" data-placement="top">
        </div>
      {% endfor %}
    </div>
  </div>
</div>

froide_govplan/templates/froide_govplan/plugins/progress_row.html
{% load govplan %}

{% get_plan_progress object_list as progress %}

<div class="row">
  <div class="col-sm-3">
    <span class="text-body-secondary{% if not instance.extra_classes or "progress-lg" not in instance.extra_classes %} small{% endif %}">{{ progress.count }} Vorhaben</span>
  </div>
  <div class="col-sm-9">
    <div class="progress" {% if "progress-lg" in instance.extra_classes %}style="height: 1.5rem;"{% endif %}>
      {% for section in progress.sections %}
        <div class="progress-bar bg-{{ section.css_class }}" role="progressbar" style="width: {{ section.css_percentage }}%;" aria-valuenow="{{ section.css_percentage }}" aria-valuemin="0" aria-valuemax="100" aria-label="{{ section.percentage }}% {{ section.label }}" title="{{ section.percentage }}% {{ section.label }}" data-bs-toggle="tooltip" data-placement="top">
        </div>
      {% endfor %}
    </div>
  </div>
</div>

froide_govplan/templates/froide_govplan/plugins/search.html
{% load i18n %}
<form method="get" action="{% url 'govplan:search' %}" class="ajaxified" data-container="#govplan-searchresult-{{ instance.id }}" data-modalcontainer="#govplan-searchmodal-{{ instance.id }}">
  <div class="input-group">
    <input type="text" name="q" class="form-control" aria-label="{% translate 'Search query' %}" placeholder="{% translate 'Search query' %}">
    <select name="status" class="form-select">
      <option value="">{% translate "Filter status" %}</option>
      {% for status, label in status_list %}
        <option value="{{ status }}">{{ label }}</option>
      {% endfor %}
    </select>
    <button class="btn btn-outline-secondary" type="submit">
      {% translate "Search" %}
    </button>
  </div>
  {% if instance.government_id %}
    <input type="hidden" name="government" value="{{ instance.government_id }}"/>
  {% endif %}
</form>

<div class="modal fade" id="govplan-searchmodal-{{ instance.id }}">
  <div class="modal-dialog modal-dialog-centered modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans "Search results" %}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate 'Close' %}">
        </button>
      </div>
      <div class="modal-body">
        <div id="govplan-searchresult-{{ instance.id }}"></div>
      </div>
    </div>
  </div>
</div>

froide_govplan/templates/froide_govplan/plugins/sections.html
{% load thumbnail %}
{% load govplan %}

<style>
  {% for section in sections %}
  {% if section.image %}
  #govsection-{{ section.pk }}::after {
    background-image: url('{% thumbnail section.image 350x150 crop subject_location=section.image.subject_location %}');
  }
  {% endif %}
  {% endfor %}
</style>

<style>
  /* Add this CSS rule to remove the margin on h3 elements inside box-card */
  .box-card h3 {
    margin: 0;
  }
</style>

<div class="row">
  {% for section in sections %}
  <div class="col col-12 col-md-4 mb-3 d-flex align-items-stretch">
    <a href="{{ section.get_absolute_url }}" class="d-flex w-100 text-body text-decoration-none">
      <div class="card-wrapper" style="border: 1px solid #000000; width: 100%;">
        <div class="box-card border-blue mb-0 d-flex flex-column">
          <div class="box-card-header tight-margin d-flex align-items-center has-background p-3 p-md-4 text-bg-callout" id="govsection-{{ section.pk }}" style="background-color: #502379;">
            <h3 class="h5 m-0" style="color: #ffffff;">
              {{ section.title }}
            </h3> 
            {% if section.icon %}
            <div class="ms-auto">
              <div class="box-card-icon position-static text-bg-body">
                <i class="fa fa-{{ section.icon }}"></i>
              </div>
            </div>
            {% endif %}
          </div>
          <div class="p-3 tight-margin d-flex flex-column">
            {% get_section_progress section %}
          </div>
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>

froide_govplan/templates/froide_govplan/plugins/time_used.html
{% load govplan %}

{% load i18n %}

<div class="row">
  {% with gov=instance.government %}
    <div class="col-sm-3">
      <span class="text-body-secondary">
        {% blocktranslate count days=gov.days_left %}One day left{% plural %}{{ days }} days left{% endblocktranslate %}
      </span>
    </div>
    <div class="col-sm-9">
      <div class="progress" style="height: 1.5rem;">
          <div class="progress-bar bg-secondary"  role="progressbar" style="width: {{ gov.days_used_percentage }}%;" aria-valuenow="{{ gov.days_used_percentage }}" aria-valuemin="0" aria-valuemax="100" aria-label="{{ gov.days_used_percentage }}%" title="{{ gov.days_used_percentage }}%" data-bs-toggle="tooltip" data-placement="top">
          </div>
      </div>
    </div>
  {% endwith %}
</div>

froide_govplan/templates/froide_govplan/plugins/updates.html
{% load markup %}

{% for update in updates %}
{% if wrapper_classes %}<div class="{{ wrapper_classes }}">{% endif %}
<div class="box-card border-blue shadow-blue bg-body" id="update-{{ update.pk }}">
  <a href="{{ update.get_absolute_url }}" class="text-body text-decoration-none">
    <div class="box-card-header text-bg-callout d-flex justify-content-center p-3 p-md-4 tight-margin flex-column">
      <div>
        {% if show_context %}
          <span class="badge text-bg-blue-100 rounded-pill float-md-right mb-2 mb-md-0">
            {{ update.plan.get_section }}
          </span>
        {% endif %}
        
        {% if show_context %}
          <h3 class="h5 mt-0">{{ update.plan }}</h3>
        {% else %}
          <h3 class="h4 mt-0">{{ update.title }}</h3>
        {% endif %}
      </div>
      <div class="small">
        <time datetime="{{ update.timestamp|date:'c' }}">{{ update.timestamp|date:"DATE_FORMAT" }}</time>

        {% if update.user or update.organization %}
        <span>
          von {{ update.user.get_full_name }}{% if update.user and update.organization %},{% endif %}
          {{ update.organization.name }}
        </span>
        {% endif %}
      </div>
    </div>
  </a>

  {% if update.content or show_context %}
  <div class="p-3 p-md-4 tight-margin">
    {% if show_context %}
      <h4 class="h5">{{ update.title }}</h4>
    {% endif %}

    {% with update.content|markdown as content %}
      {% if show_context %}
        {{ content|truncatewords_html:50 }}
      {% else %}
        {{ content }}
      {% endif %}
    {% endwith %}
  </div>
  {% endif %}

  {% if update.url or update.foirequest or show_context %}
  <div class="p-3 p-md-4 {% if update.content %}box-card-links{% else %}d-flex mt-auto{% endif %}">
    {% if show_context %}
      <a href="{{ update.get_absolute_url }}" class="action-link">→ zum Vorhaben</a>
    {% else %}
      {% if update.url %}
        <a href="{{ update.url }}" class="action-link me-3" target="_blank" rel="noopener">→ mehr auf {{ update.get_url_domain }} lesen…</a>
      {% endif %}

      {% if update.foirequest %}
        <a href="{{ update.foirequest.get_absolute_url }}" class="action-link">→ zur Anfrage</a>
      {% endif %}
    {% endif %}
  </div>
  {% endif %}
</div>
{% if wrapper_classes %}</div>{% endif %}
{% endfor %}