froide_govplan/urls.py
from django.urls import path
from django.utils.translation import pgettext_lazy

from .views import (
    GovPlanDetailView,
    GovPlanProposeUpdateView,
    GovPlanSectionDetailView,
    search,
)

app_name = "govplan"

urlpatterns = [
    path("search/", search, name="search"),
    path(
        pgettext_lazy("url part", "<slug:gov>/plan/<slug:plan>/"),
        GovPlanDetailView.as_view(),
        name="plan",
    ),
    path(
        pgettext_lazy("url part", "<slug:gov>/plan/<slug:plan>/propose-update/"),
        GovPlanProposeUpdateView.as_view(),
        name="propose_planupdate",
    ),
    path(
        pgettext_lazy("url part", "<slug:gov>/<slug:section>/"),
        GovPlanSectionDetailView.as_view(),
        name="section",
    ),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(
        "follow/",
        include("froide.follow.urls", namespace="follow"),
    ),
    path("admin/", admin.site.urls),
    path("", include("cms.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

froide_govplan/models.py
import functools
import re
from datetime import timedelta
from urllib.parse import urlparse

from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from filer.fields.image import FilerImageField
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase

from froide.follow.models import Follower
from froide.georegion.models import GeoRegion
from froide.organization.models import Organization
from froide.publicbody.models import Category, Jurisdiction, PublicBody

from . import conf
from .utils import make_request_url

try:
    from cms.models.fields import PlaceholderField
    from cms.models.pluginmodel import CMSPlugin
except ImportError:
    CMSPlugin = None
    PlaceholderField = None


if conf.GOVPLAN_ENABLE_FOIREQUEST:
    from froide.foirequest.models import FoiRequest
else:
    FoiRequest = None


class PlanStatus(models.TextChoices):
    NOT_STARTED = ("not_started", _("nicht begonnen"))
    STARTED = ("started", _("begonnen"))
    PARTIALLY_IMPLEMENTED = ("partially_implemented", _("teilweise umgesetzt"))
    IMPLEMENTED = ("implemented", _("umgesetzt"))
    DEFERRED = ("deferred", _("verschoben"))


STATUS_CSS = {
    PlanStatus.NOT_STARTED: "light",
    PlanStatus.STARTED: "primary",
    PlanStatus.PARTIALLY_IMPLEMENTED: "warning",
    PlanStatus.IMPLEMENTED: "success",
    PlanStatus.DEFERRED: "danger",
}


class PlanRating(models.IntegerChoices):
    TERRIBLE = 1, _("terrible")
    BAD = 2, _("bad")
    OK = 3, _("OK")
    GOOD = 4, _("good")
    EXCELLENT = 5, _("excellent")


class Government(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("name"))
    slug = models.SlugField(max_length=255, unique=True, verbose_name=_("slug"))

    public = models.BooleanField(default=False, verbose_name=_("is public?"))
    jurisdiction = models.ForeignKey(
        Jurisdiction,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("jurisdiction"),
    )
    georegion = models.ForeignKey(
        GeoRegion,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("georegion"),
    )
    description = models.TextField(blank=True, verbose_name=_("description"))

    start_date = models.DateField(null=True, blank=True, verbose_name=_("start date"))
    end_date = models.DateField(null=True, blank=True, verbose_name=_("end date"))

    planning_document = models.URLField(blank=True, verbose_name=_("planning document"))

    class Meta:
        verbose_name = _("Government")
        verbose_name_plural = _("Governments")

    def __str__(self):
        return self.name

    @property
    def days_available(self):
        if self.start_date is None:
            return 0
        if self.end_date is None:
            return 0
        return (self.end_date - self.start_date).days

    @property
    def days_left(self):
        if not self.end_date:
            return 0
        now = timezone.now().date()
        if now > self.end_date:
            return 0
        return (self.end_date - now).days

    def days_used_percentage(self) -> int:
        total_days = self.days_available
        if not total_days:
            return 0
        now = timezone.now().date()
        days_used = (now - self.start_date).days
        return int(days_used / total_days * 100)


class CategorizedGovernmentPlan(TaggedItemBase):
    tag = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="categorized_governmentplan"
    )
    content_object = models.ForeignKey("GovernmentPlan", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Categorized Government Plan")
        verbose_name_plural = _("Categorized Government Plans")


WORD_RE = re.compile(r"^\w+$", re.IGNORECASE)


class GovernmentPlanManager(models.Manager):
    SEARCH_LANG = "german"

    def get_search_vector(self):
        fields = [
            ("title", "A"),
            ("description", "B"),
            ("quote", "B"),
        ]
        return functools.reduce(
            lambda a, b: a + b,
            [SearchVector(f, weight=w, config=self.SEARCH_LANG) for f, w in fields],
        )

    def search(self, query, qs=None):
        if not qs:
            qs = self.get_queryset()
        query = query.strip()
        if not query:
            return qs
        search_queries = []
        for q in query.split():
            q = q.strip()
            if not q:
                continue
            if WORD_RE.match(q):
                sq = SearchQuery(
                    "{}:*".format(q), search_type="raw", config=self.SEARCH_LANG
                )
            else:
                sq = SearchQuery(q, search_type="plain", config=self.SEARCH_LANG)
            search_queries.append(sq)

        if not search_queries:
            return qs
        search_query = functools.reduce(lambda a, b: a & b, search_queries)

        search_vector = self.get_search_vector()
        qs = (
            qs.annotate(rank=SearchRank(search_vector, search_query))
            .filter(rank__gte=0.1)
            .order_by("-rank")
        )
        return qs


class GovernmentPlan(models.Model):
    government = models.ForeignKey(
        Government, on_delete=models.CASCADE, verbose_name=_("government")
    )
    title = models.CharField(max_length=255, verbose_name=_("title"))
    slug = models.SlugField(max_length=255, unique=True, verbose_name=_("slug"))

    image = FilerImageField(
        null=True,
        blank=True,
        default=None,
        verbose_name=_("image"),
        on_delete=models.SET_NULL,
    )

    description = models.TextField(blank=True, verbose_name=_("description"))
    quote = models.TextField(blank=True, verbose_name=_("quote"))
    public = models.BooleanField(default=False, verbose_name=_("is public?"))
    due_date = models.DateField(null=True, blank=True, verbose_name=_("due date"))
    measure = models.CharField(max_length=255, blank=True, verbose_name=_("measure"))

    status = models.CharField(
        max_length=25,
        choices=PlanStatus.choices,
        default="not_started",
        verbose_name=_("status"),
    )
    rating = models.IntegerField(
        choices=PlanRating.choices, null=True, blank=True, verbose_name=_("rating")
    )

    reference = models.CharField(
        max_length=255, blank=True, verbose_name=_("reference")
    )

    categories = TaggableManager(
        through=CategorizedGovernmentPlan, verbose_name=_("categories"), blank=True
    )
    responsible_publicbody = models.ForeignKey(
        PublicBody,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("responsible public body"),
    )

    organization = models.ForeignKey(
        Organization,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("organization"),
    )

    group = models.ForeignKey(
        Group, null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_("group")
    )

    proposals = models.JSONField(blank=True, null=True)
    properties = models.JSONField(blank=True, default=dict)

    objects = GovernmentPlanManager()

    class Meta:
        ordering = ("reference", "title")
        verbose_name = _("Government plan")
        verbose_name_plural = _("Government plans")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "govplan:plan", kwargs={"gov": self.government.slug, "plan": self.slug}
        )

    def get_absolute_domain_url(self):
        return settings.SITE_URL + self.get_absolute_url()

    def get_absolute_short_url(self):  # Return long url as short url for update emails
        return self.get_absolute_url()

    def get_absolute_domain_short_url(self):
        return settings.SITE_URL + self.get_absolute_short_url()

    def get_reference_links(self):
        if self.reference.startswith("https://"):
            return [self.reference]
        refs = [x.strip() for x in self.reference.split(",")]
        return [
            "{}#p-{}".format(self.government.planning_document, ref) for ref in refs
        ]

    def get_section(self):
        return GovernmentPlanSection.objects.filter(
            categories__in=self.categories.all()
        ).first()

    def update_from_updates(self):
        last_status_update = (
            self.updates.all().filter(public=True).exclude(status="").first()
        )
        if last_status_update:
            self.status = last_status_update.status
        last_rating_update = (
            self.updates.all().filter(public=True).exclude(rating=None).first()
        )
        if last_rating_update:
            self.rating = last_rating_update.rating
        if last_status_update or last_rating_update:
            self.save()

    def get_status_css(self):
        return STATUS_CSS.get(self.status, "")

    def make_request_url(self):
        if not self.responsible_publicbody:
            return []
        return make_request_url(self, self.responsible_publicbody)

    def has_recent_foirequest(self):
        frs = self.get_related_foirequests()
        ago = timezone.now() - timedelta(days=90)
        return any(fr.created_at > ago for fr in frs)

    def get_recent_foirequest(self):
        return self.get_related_foirequests()[0]

    def get_foirequest_reference(self):
        return "govplan:plan@{}".format(self.pk)

    def get_related_foirequests(self):
        if FoiRequest is None:
            return []
        if not self.responsible_publicbody:
            return []
        if hasattr(self, "_related_foirequests"):
            return self._related_foirequests

        self._related_foirequests = (

froide_govplan/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, UpdateView

from .auth import get_visible_plans
from .forms import GovernmentPlanUpdateProposalForm
from .models import Government, GovernmentPlan, GovernmentPlanSection


class GovernmentMixin:
    def dispatch(self, *args, **kwargs):
        self.get_government()
        return super().dispatch(*args, **kwargs)

    def get_government(self):
        filter_kwarg = {}
        if not self.request.user.is_authenticated or not self.request.user.is_staff:
            filter_kwarg["public"] = True
        self.government = get_object_or_404(
            Government, slug=self.kwargs["gov"], **filter_kwarg
        )


class GovPlanSectionDetailView(GovernmentMixin, DetailView):
    slug_url_kwarg = "section"
    template_name = "froide_govplan/section.html"

    def get_queryset(self):
        return GovernmentPlanSection.objects.filter(
            government=self.government
        ).select_related("government")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = get_visible_plans(self.request)
        context["plans"] = context["object"].get_plans(queryset=queryset)
        return context


class GovPlanDetailView(GovernmentMixin, DetailView):
    slug_url_kwarg = "plan"
    template_name = "froide_govplan/detail.html"

    def get_queryset(self):
        qs = GovernmentPlan.objects.filter(government=self.government)
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return qs
        return qs.filter(public=True).select_related(
            "responsible_publicbody", "organization"
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["updates"] = self.object.updates.filter(public=True).order_by(
            "-timestamp"
        )
        context["section"] = self.object.get_section()
        if self.request.user.is_authenticated:
            context["update_proposal_form"] = GovernmentPlanUpdateProposalForm()
        # For CMS toolbar
        self.request.govplan = self.object
        return context


class GovPlanProposeUpdateView(GovernmentMixin, LoginRequiredMixin, UpdateView):
    slug_url_kwarg = "plan"
    form_class = GovernmentPlanUpdateProposalForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return redirect(self.object)

    def get_queryset(self):
        qs = GovernmentPlan.objects.filter(government=self.government)
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return qs
        return qs.filter(public=True)

    def get_success_url(self):
        return self.object.get_absolute_url()

    def form_valid(self, form):
        form.save(self.object, self.request.user)
        messages.add_message(
            self.request,
            messages.INFO,
            _(
                "Thank you for your proposal. We will send you an email when it has been approved."
            ),
        )
        return redirect(self.object)

    def form_invalid(self, form):
        messages.add_message(
            self.request,
            messages.ERROR,
            _("There's been an error with your form submission."),
        )
        return redirect(self.object)


def search(request):
    q = request.GET.get("q", "")
    plans = GovernmentPlan.objects.filter(public=True)
    if q:
        plans = GovernmentPlan.objects.search(q, qs=plans)

    if request.GET.get("government"):
        try:
            gov_id = int(request.GET["government"])
            plans = plans.filter(government_id=gov_id)
        except ValueError:
            pass
    if request.GET.get("status"):
        try:
            status = request.GET["status"]
            plans = plans.filter(status=status)
        except ValueError:
            pass

    if q:
        # limit when there's a search
        plans = plans[:20]
    return render(
        request, "froide_govplan/plugins/card_cols.html", {"object_list": plans}
    )

froide_govplan/templates/froide_govplan/base.html
{% extends "cms/page.html" %}

{% load cms_tags %}
{% load menu_tags %}

{% block navbar %}
  {% include "header_reduced.html" %}
{% endblock %}

{% block body %}
  <!-- <nav class="bg-body-secondary" aria-label="breadcrumb">
    <div class="container">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ request.current_page.get_absolute_url }}">
            {{ request.current_page.get_title }}
          </a>
        </li>
        {% block govplan_breadcrumbs %}{% endblock %}
      </ol>
    </div>
  </nav> -->

  {% static_placeholder "govplan_header" %}
  {% block app_body %}
    {% placeholder "content" %}
  {% endblock %}
  {% static_placeholder "govplan_footer" %}
{% endblock %}

froide_govplan/templates/froide_govplan/detail.html
{% extends "froide_govplan/base.html" %}

{% load i18n %} {# TODO: i18n for all strings #}
{% load markup %}
{% load cms_tags %}
{% load follow_tags %}
{% load govplan %}
{% load form_helper %}
{% load content_helper %}
{% load thumbnail %}

{% block title %}{{ object.title }}{% endblock %}

{% block meta %}
  {% include "snippets/meta.html" %}
{% endblock %}

{% block govplan_breadcrumbs %}
<li class="breadcrumb-item">
  <a href="{{ section.get_absolute_url }}">{{ section.title}}</a>
</li>
<li class="breadcrumb-item active" aria-current="page">
  <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
</li>
{% endblock %}

{% block app_body %}
<div class="container mb-3">
  <div class="box-card border-yellow md:shadow-yellow bg-body mb-5">
    <div>
      <div class="flex-grow-1 tight-margin p-3 p-md-4 p-lg-5">
        <h1 class="mt-0 h3">
          {{ object.title }}
        </h1>

        <div class="d-md-flex my-4 align-items-center">
          <ul class="list-unstyled d-flex m-0">
            <li>
              <span class="badge text-bg-{{ object.get_status_css }} me-2">
                {{ object.get_status_display }}
              </span>
            </li>
            {% for cat in object.categories.all %}
            <li>
              <a href="{{ section.get_absolute_url }}" class="badge text-bg-light-subtle me-2">
                {{ cat.name }}
              </a>
            </li>
            {% endfor %}
          </ul>

          <div class="ms-auto mt-2 mt-md-0">
            {% show_follow "govplan" object %}
          </div>
        </div>

        <div class="row">
          <div class="col col-12 col-md-7 col-lg-8 order-md-2 offset-lg-1">
            <dl>
              {% if object.quote %}
                <dt>Ausschnitt aus dem Wahlprogramm</dt>
                <dd>
                  <blockquote>
                    {{ object.quote | addquotes | markdown }}
                  </blockquote>
                {% with refs=object.get_reference_links %}
                  {% if refs %}
                    <p>
                      <span class="small">
                      {% if refs|length > 1 %}
                        Quellen:
                      {% else %}
                        Quelle:
                      {% endif %}
                      </span>
                      {% for ref in refs %}
                        <a href="{{ ref }}" class="badge text-bg-light me-2" target="_blank">
                          {{ forloop.counter }}
                        </a>
                      {% endfor %}
                    </p>
                  {% endif %}
                {% endwith %}
                {% endif %}
              </dd>

              {% if object.description %}
                <div class="mt-3 mt-md-5">
                  <dt>Unsere Einschätzung</dt>
                  <dd>{{ object.description | safe }}</dd>
                </div>
              {% endif %}
            </dl>
          </div>
          <div class="col col-12 col-md-5 col-lg-3 mt-3 mt-md-0">
            <dl>
              {% if object.rating %}
                <dt>Bewertung</dt>
                <dd>{{ object.get_rating_display }}</dd>
              {% endif %}

              {% if object.measure %}
                <dt>Art der Umsetzung</dt>
                <dd>{{ object.measure }}</dd>
              {% endif %}

              {% if object.due_date %}
                <dt>Frist</dt>
                <dd>{{ object.due_date|date:"SHORT_DATE_FORMAT" }}</dd>
              {% endif %}

              {% if object.responsible_publicbody %}
                <dt>Federführung</dt>
                <dd>
                  <a href="{{ object.responsible_publicbody.get_absolute_url }}">
                    {{ object.responsible_publicbody.name }}
                  </a>
                </dd>
              {% endif %}

              {% if object.responsible_publicbody %}
                {% if not object.has_recent_foirequest %}
                  <p>
                    <a href="{{ object.make_request_url }}" target="_blank" class="btn btn-outline-primary btn-sm">
                      Anfrage zum Vorhaben stellen
                    </a>
                  </p>
                {% else %}
                  {% with foirequest=object.get_recent_foirequest %}
                  <dt>Anfrage</dt>
                  <dd>
                    {% include "foirequest/snippets/request_item_mini.html" with object=foirequest %}
                  </dd>
                  {% endwith %}
                {% endif %}
              {% endif %}

              {% if object.organization %}
                <dt>Beobachtet von</dt>
                <dd>
                  <a href="{{ object.organization.website }}">
                    {% if object.organization.logo %}
                      {% if object.organization.logo.url.lower|slice:"-4:" == ".svg" %}
                      <img src="{{ object.organization.logo.url }}" class="col-8 col-md-12 px-0" alt="{{ object.organization.name }}">
                      {% else %}
                      <img src="{% thumbnail object.organization.logo 300x0 %}" class="col-8 col-md-12 px-0" alt="{{ object.organization.name }}">
                      {% endif %}
                    {% else %}
                    {{ object.organization.name }}
                    {% endif %}
                  </a>
                </dd>
              {% endif %}
            </dl>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    {% include "froide_govplan/plugins/updates.html" with wrapper_classes="col col-12 col-lg-6 d-flex mb-4" %}

    <div class="col col-12 col-lg-6 d-flex mb-4">
      <div class="box-card border-gray shadow-gray">
        <div>
          <div class="box-card-header text-bg-body-tertiary d-flex justify-content-center p-3 p-md-4 tight-margin flex-column">
            <h3 class="h4">Neue Entwicklung melden</h3>
          </div>
          <div class="p-3 p-md-4">
            {% if request.user.is_authenticated %}
              <p>Gibt es Neuigkeiten zu diesem Vorhaben, die wir noch nicht erfasst haben?</p>
              <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#govplanupdate-proposal">
                Entwicklung melden
              </button>
              <div class="modal" data-teleport="body" tabindex="-1" role="dialog" id="govplanupdate-proposal">
                <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">
                        Neue Entwicklung melden
                      </h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate 'Close' %}">
                      </button>
                    </div>
                    <div class="modal-body">
                      <form method="post" action="{% url 'govplan:propose_planupdate' gov=object.government.slug plan=object.slug %}">
                        {% csrf_token %}
                        {% render_form update_proposal_form %}
                        <button type="submit" class="btn btn-primary">
                          Neue Entwicklung melden
                        </button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            {% else %}
              Bitte <a href="{{ object.get_absolute_url|make_login_redirect_url }}">melden Sie sich an</a>, um einen Änderungsvorschlag einzureichen.
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>


</div>
{% endblock %}

froide_govplan/templates/froide_govplan/section.html
{% extends "froide_govplan/base.html" %}

{% load i18n %}
{% load markup %}
{% load cms_tags %}
{% load follow_tags %}
{% load thumbnail %}

{% block title %}{{ object.title }}{% endblock %}

{% block meta %}
  {% include "snippets/meta.html" %}
{% endblock %}

{% block govplan_breadcrumbs %}
<li class="breadcrumb-item active" aria-current="page">
  <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
</li>
{% endblock %}

{% block app_body %}
<div class="container">
  <div class="row justify-content-center mb-5">  
    <div class="col col-lg-12">
      <div class="box-card border-yellow md:shadow-yellow bg-body p-3 p-md-4 p-lg-5 tight-margin">
        <div class="row mx-0">
          <div class="col col-12 col-md-12 ps-0 tight-margin">
            <h1 class="mt-0 h2">
              {{ object.title }}
            </h1>

            <p>
              {% blocktranslate with section=object.title %}
              Hier finden Sie alle Pläne der Sektion “{{ section }}”, die Volt Aachen in ihrem Wahlprogramm 2020 festgelegt hat.
              Auf den jeweiligen Detailseiten können Sie sich weiter informieren und über Neuigkeiten auf dem Laufenden bleiben.
              {% endblocktranslate %}
            </p>
          </div>
        </div>

        <div class="mt-5">
          {% include "froide_govplan/plugins/progress_row.html" with object_list=plans %}
          <p class="small text-body-secondary mt-3 no-hyphens">
            <span class="text-nowrap me-1"><i class="fa fa-circle text-light"></i>&nbsp;nicht begonnen</span>
            <span class="text-nowrap me-1"><i class="fa fa-circle text-primary"></i>&nbsp;begonnen</span>
            <span class="text-nowrap me-1"><i class="fa fa-circle text-warning"></i>&nbsp;teilweise umgesetzt</span>
            <span class="text-nowrap me-1"><i class="fa fa-circle text-success"></i>&nbsp;umgesetzt</span>
            <span class="text-nowrap me-1"><i class="fa fa-circle text-danger"></i>&nbsp;verschoben</span>
          </p>          
          {% include "froide_govplan/plugins/time_used.html" with instance=object %}
        </div>
      </div>
    </div>
  </div>
    
  {% include "froide_govplan/plugins/card_cols.html" with object_list=plans %}
</div>
{% endblock %}